
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by SEO houltman 1.0 -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<!--
    <url>
        <loc>https://damecoins.com</loc>
		<changefreq>monthly</changefreq>
		<priority>0.1</priority>
    </url>
    <url>
        <loc>https://damecoins.com/login</loc>
		<changefreq>monthly</changefreq>
		<priority>0.8</priority>
    </url>
    <url>
        <loc>https://damecoins.com/signup</loc>
		<changefreq>weekly</changefreq>
		<priority>0,8</priority>
    </url>
    -->

    @foreach ($criptos as $cripto)
        @foreach ($currencies as $currency)
            <url>
                <loc>https://damecoins.com/يشترى-{{ strtolower($cripto->code) }}/with-credit-card-in-{{ strtolower($currency->code) }}</loc>
                <changefreq>daily</changefreq>
		        <priority>1</priority>
            </url>
            <url>
                <loc>https://damecoins.com/खरीद सकते हैं-{{ strtolower($cripto->code) }}/चुनाव-कार्ड-इन-{{ strtolower($currency->code) }}</loc>
                <changefreq>daily</changefreq>
		        <priority>1</priority>
            </url>
            
        @endforeach
    @endforeach
</urlset>