<?php

use Illuminate\Database\Seeder;
use Faker\Factory as Faker;
use Illuminate\Support\Facades\DB;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		$paises = [
			['cod'=>'af','nombre'=>'Afganistán','ico'=>'flag-icon-af'],
			['cod'=>'al','nombre'=>'Albania','ico'=>'flag-icon-al'],
			['cod'=>'de','nombre'=>'Alemania','ico'=>'flag-icon-de'],
			['cod'=>'ad','nombre'=>'Andorra','ico'=>'flag-icon-ad'],
			['cod'=>'ao','nombre'=>'Angola','ico'=>'flag-icon-ao'],
			['cod'=>'ag','nombre'=>'Antigua y Barbuda','ico'=>'flag-icon-ag'],
			['cod'=>'sa','nombre'=>'Arabia Saudita','ico'=>'flag-icon-sa'],
			['cod'=>'dz','nombre'=>'Argelia','ico'=>'flag-icon-dz'],
			['cod'=>'ar','nombre'=>'Argentina','ico'=>'flag-icon-ar'],
			['cod'=>'am','nombre'=>'Armenia','ico'=>'flag-icon-am'],
			['cod'=>'au','nombre'=>'Australia','ico'=>'flag-icon-au'],
			['cod'=>'at','nombre'=>'Austria','ico'=>'flag-icon-at'],
			['cod'=>'az','nombre'=>'Azerbaiyán','ico'=>'flag-icon-az'],
			['cod'=>'bs','nombre'=>'Bahamas','ico'=>'flag-icon-bs'],
			['cod'=>'bd','nombre'=>'Bangladesh','ico'=>'flag-icon-bd'],
			['cod'=>'bb','nombre'=>'Barbados','ico'=>'flag-icon-bb'],
			['cod'=>'bh','nombre'=>'Baréin','ico'=>'flag-icon-bh'],
			['cod'=>'be','nombre'=>'Bélgica','ico'=>'flag-icon-be'],
			['cod'=>'bz','nombre'=>'Belice','ico'=>'flag-icon-bz'],
			['cod'=>'bj','nombre'=>'Benín','ico'=>'flag-icon-bj'],
			['cod'=>'by','nombre'=>'Bielorrusia','ico'=>'flag-icon-by'],
			['cod'=>'bo','nombre'=>'Bolivia','ico'=>'flag-icon-bo'],
			['cod'=>'ba','nombre'=>'Bosnia y Herzegovina','ico'=>'flag-icon-ba'],
			['cod'=>'bw','nombre'=>'Botsuana','ico'=>'flag-icon-bw'],
			['cod'=>'br','nombre'=>'Brasil','ico'=>'flag-icon-br'],
			['cod'=>'bn','nombre'=>'Brunei Darussalam','ico'=>'flag-icon-bn'],
			['cod'=>'bg','nombre'=>'Bulgaria','ico'=>'flag-icon-bg'],
			['cod'=>'bf','nombre'=>'Burkina Faso','ico'=>'flag-icon-bf'],
			['cod'=>'bi','nombre'=>'Burundi','ico'=>'flag-icon-bi'],
			['cod'=>'bt','nombre'=>'Bután','ico'=>'flag-icon-bt'],
			['cod'=>'cv','nombre'=>'Cabo Verde','ico'=>'flag-icon-cv'],
			['cod'=>'kh','nombre'=>'Camboya','ico'=>'flag-icon-kh'],
			['cod'=>'cm','nombre'=>'Camerún','ico'=>'flag-icon-cm'],
			['cod'=>'ca','nombre'=>'Canadá','ico'=>'flag-icon-ca'],
			['cod'=>'td','nombre'=>'Chad','ico'=>'flag-icon-td'],
			['cod'=>'cz','nombre'=>'Chequia','ico'=>'flag-icon-cz'],
			['cod'=>'cl','nombre'=>'Chile','ico'=>'flag-icon-cl'],
			['cod'=>'cn','nombre'=>'China','ico'=>'flag-icon-cn'],
			['cod'=>'cy','nombre'=>'Chipre','ico'=>'flag-icon-cy'],
			['cod'=>'co','nombre'=>'Colombia','ico'=>'flag-icon-co'],
			['cod'=>'km','nombre'=>'Comoras','ico'=>'flag-icon-km'],
			['cod'=>'cg','nombre'=>'Congo','ico'=>'flag-icon-cg'],
			['cod'=>'ci','nombre'=>'Costa de Marfil','ico'=>'flag-icon-ci'],
			['cod'=>'cr','nombre'=>'Costa Rica','ico'=>'flag-icon-cr'],
			['cod'=>'hr','nombre'=>'Croacia','ico'=>'flag-icon-hr'],
			['cod'=>'cu','nombre'=>'Cuba','ico'=>'flag-icon-cu'],
			['cod'=>'dk','nombre'=>'Dinamarca','ico'=>'flag-icon-dk'],
			['cod'=>'dm','nombre'=>'Dominica','ico'=>'flag-icon-dm'],
			['cod'=>'ec','nombre'=>'Ecuador','ico'=>'flag-icon-ec'],
			['cod'=>'eg','nombre'=>'Egipto','ico'=>'flag-icon-eg'],
			['cod'=>'sv','nombre'=>'El Salvador','ico'=>'flag-icon-sv'],
			['cod'=>'ae','nombre'=>'Emiratos Árabes Unidos','ico'=>'flag-icon-ae'],
			['cod'=>'er','nombre'=>'Eritrea','ico'=>'flag-icon-er'],
			['cod'=>'sk','nombre'=>'Eslovaquia','ico'=>'flag-icon-sk'],
			['cod'=>'si','nombre'=>'Eslovenia','ico'=>'flag-icon-si'],
			['cod'=>'es','nombre'=>'España','ico'=>'flag-icon-es'],
			['cod'=>'us','nombre'=>'Estados Unidos de América','ico'=>'flag-icon-us'],
			['cod'=>'ee','nombre'=>'Estonia','ico'=>'flag-icon-ee'],
			['cod'=>'et','nombre'=>'Etiopía','ico'=>'flag-icon-et'],
			['cod'=>'mk','nombre'=>'Ex República Yugoslava de Macedonia','ico'=>'flag-icon-mk'],
			['cod'=>'ru','nombre'=>'Federación de Rusia','ico'=>'flag-icon-ru'],
			['cod'=>'ph','nombre'=>'Filipinas','ico'=>'flag-icon-ph'],
			['cod'=>'fi','nombre'=>'Finlandia','ico'=>'flag-icon-fi'],
			['cod'=>'fj','nombre'=>'Fiyi','ico'=>'flag-icon-fj'],
			['cod'=>'fr','nombre'=>'Francia','ico'=>'flag-icon-fr'],
			['cod'=>'ga','nombre'=>'Gabón','ico'=>'flag-icon-ga'],
			['cod'=>'gm','nombre'=>'Gambia','ico'=>'flag-icon-gm'],
			['cod'=>'ge','nombre'=>'Georgia','ico'=>'flag-icon-ge'],
			['cod'=>'gh','nombre'=>'Ghana','ico'=>'flag-icon-gh'],
			['cod'=>'gd','nombre'=>'Granada','ico'=>'flag-icon-gd'],
			['cod'=>'gr','nombre'=>'Grecia','ico'=>'flag-icon-gr'],
			['cod'=>'gt','nombre'=>'Guatemala','ico'=>'flag-icon-gt'],
			['cod'=>'gn','nombre'=>'Guinea','ico'=>'flag-icon-gn'],
			['cod'=>'gq','nombre'=>'Guinea Ecuatorial','ico'=>'flag-icon-gq'],
			['cod'=>'gw','nombre'=>'Guinea-Bissau','ico'=>'flag-icon-gw'],
			['cod'=>'gy','nombre'=>'Guyana','ico'=>'flag-icon-gy'],
			['cod'=>'ht','nombre'=>'Haití','ico'=>'flag-icon-ht'],
			['cod'=>'hn','nombre'=>'Honduras','ico'=>'flag-icon-hn'],
			['cod'=>'hu','nombre'=>'Hungría','ico'=>'flag-icon-hu'],
			['cod'=>'in','nombre'=>'India','ico'=>'flag-icon-in'],
			['cod'=>'id','nombre'=>'Indonesia','ico'=>'flag-icon-id'],
			['cod'=>'ir','nombre'=>'Irán','ico'=>'flag-icon-ir'],
			['cod'=>'iq','nombre'=>'Iraq','ico'=>'flag-icon-iq'],
			['cod'=>'ie','nombre'=>'Irlanda','ico'=>'flag-icon-ie'],
			['cod'=>'is','nombre'=>'Islandia','ico'=>'flag-icon-is'],
			['cod'=>'ck','nombre'=>'Islas Cook','ico'=>'flag-icon-ck'],
			['cod'=>'fo','nombre'=>'Islas Feroe','ico'=>'flag-icon-fo'],
			['cod'=>'mh','nombre'=>'Islas Marshall','ico'=>'flag-icon-mh'],
			['cod'=>'sb','nombre'=>'Islas Salomón','ico'=>'flag-icon-sb'],
			['cod'=>'il','nombre'=>'Israel','ico'=>'flag-icon-il'],
			['cod'=>'it','nombre'=>'Italia','ico'=>'flag-icon-it'],
			['cod'=>'jm','nombre'=>'Jamaica','ico'=>'flag-icon-jm'],
			['cod'=>'jp','nombre'=>'Japón','ico'=>'flag-icon-jp'],
			['cod'=>'jo','nombre'=>'Jordania','ico'=>'flag-icon-jo'],
			['cod'=>'kz','nombre'=>'Kazajstán','ico'=>'flag-icon-kz'],
			['cod'=>'ke','nombre'=>'Kenia','ico'=>'flag-icon-ke'],
			['cod'=>'kg','nombre'=>'Kirguistán','ico'=>'flag-icon-kg'],
			['cod'=>'ki','nombre'=>'Kiribati','ico'=>'flag-icon-ki'],
			['cod'=>'kw','nombre'=>'Kuwait','ico'=>'flag-icon-kw'],
			['cod'=>'ls','nombre'=>'Lesoto','ico'=>'flag-icon-ls'],
			['cod'=>'lv','nombre'=>'Letonia','ico'=>'flag-icon-lv'],
			['cod'=>'lb','nombre'=>'Líbano','ico'=>'flag-icon-lb'],
			['cod'=>'lr','nombre'=>'Liberia','ico'=>'flag-icon-lr'],
			['cod'=>'ly','nombre'=>'Libia','ico'=>'flag-icon-ly'],
			['cod'=>'lt','nombre'=>'Lituania','ico'=>'flag-icon-lt'],
			['cod'=>'lu','nombre'=>'Luxemburgo','ico'=>'flag-icon-lu'],
			['cod'=>'mg','nombre'=>'Madagascar','ico'=>'flag-icon-mg'],
			['cod'=>'my','nombre'=>'Malasia','ico'=>'flag-icon-my'],
			['cod'=>'mw','nombre'=>'Malawi','ico'=>'flag-icon-mw'],
			['cod'=>'mv','nombre'=>'Maldivas','ico'=>'flag-icon-mv'],
			['cod'=>'ml','nombre'=>'Malí','ico'=>'flag-icon-ml'],
			['cod'=>'mt','nombre'=>'Malta','ico'=>'flag-icon-mt'],
			['cod'=>'ma','nombre'=>'Marruecos','ico'=>'flag-icon-ma'],
			['cod'=>'mu','nombre'=>'Mauricio','ico'=>'flag-icon-mu'],
			['cod'=>'mr','nombre'=>'Mauritania','ico'=>'flag-icon-mr'],
			['cod'=>'mx','nombre'=>'México','ico'=>'flag-icon-mx'],
			['cod'=>'fm','nombre'=>'Micronesia','ico'=>'flag-icon-fm'],
			['cod'=>'mc','nombre'=>'Mónaco','ico'=>'flag-icon-mc'],
			['cod'=>'mn','nombre'=>'Mongolia','ico'=>'flag-icon-mn'],
			['cod'=>'me','nombre'=>'Montenegro','ico'=>'flag-icon-me'],
			['cod'=>'mz','nombre'=>'Mozambique','ico'=>'flag-icon-mz'],
			['cod'=>'mm','nombre'=>'Myanmar','ico'=>'flag-icon-mm'],
			['cod'=>'na','nombre'=>'Namibia','ico'=>'flag-icon-na'],
			['cod'=>'nr','nombre'=>'Nauru','ico'=>'flag-icon-nr'],
			['cod'=>'np','nombre'=>'Nepal','ico'=>'flag-icon-np'],
			['cod'=>'ni','nombre'=>'Nicaragua','ico'=>'flag-icon-ni'],
			['cod'=>'ne','nombre'=>'Níger','ico'=>'flag-icon-ne'],
			['cod'=>'ng','nombre'=>'Nigeria','ico'=>'flag-icon-ng'],
			['cod'=>'nu','nombre'=>'Niue','ico'=>'flag-icon-nu'],
			['cod'=>'no','nombre'=>'Noruega','ico'=>'flag-icon-no'],
			['cod'=>'nz','nombre'=>'Nueva Zelandia','ico'=>'flag-icon-nz'],
			['cod'=>'om','nombre'=>'Omán','ico'=>'flag-icon-om'],
			['cod'=>'nl','nombre'=>'Países Bajos','ico'=>'flag-icon-nl'],
			['cod'=>'pk','nombre'=>'Pakistán','ico'=>'flag-icon-pk'],
			['cod'=>'pw','nombre'=>'Palaos','ico'=>'flag-icon-pw'],
			['cod'=>'pa','nombre'=>'Panamá','ico'=>'flag-icon-pa'],
			['cod'=>'pg','nombre'=>'Papúa Nueva Guinea','ico'=>'flag-icon-pg'],
			['cod'=>'py','nombre'=>'Paraguay','ico'=>'flag-icon-py'],
			['cod'=>'pe','nombre'=>'Perú','ico'=>'flag-icon-pe'],
			['cod'=>'pl','nombre'=>'Polonia','ico'=>'flag-icon-pl'],
			['cod'=>'pt','nombre'=>'Portugal','ico'=>'flag-icon-pt'],
			['cod'=>'qa','nombre'=>'Qatar','ico'=>'flag-icon-qa'],
			['cod'=>'gb','nombre'=>'Reino Unido','ico'=>'flag-icon-gb'],
			['cod'=>'sy','nombre'=>'República Árabe Siria','ico'=>'flag-icon-sy'],
			['cod'=>'cf','nombre'=>'República Centroafricana','ico'=>'flag-icon-cf'],
			['cod'=>'kr','nombre'=>'República de Corea','ico'=>'flag-icon-kr'],
			['cod'=>'md','nombre'=>'República de Moldavia','ico'=>'flag-icon-md'],
			['cod'=>'cd','nombre'=>'República Democrática del Congo','ico'=>'flag-icon-cd'],
			['cod'=>'la','nombre'=>'República Democrática Popular Lao','ico'=>'flag-icon-la'],
			['cod'=>'do','nombre'=>'República Dominicana','ico'=>'flag-icon-do'],
			['cod'=>'kp','nombre'=>'República Popular Democrática de Corea','ico'=>'flag-icon-kp'],
			['cod'=>'tz','nombre'=>'República Unida de Tanzania','ico'=>'flag-icon-tz'],
			['cod'=>'rw','nombre'=>'Ruanda','ico'=>'flag-icon-rw'],
			['cod'=>'ro','nombre'=>'Rumania','ico'=>'flag-icon-ro'],
			['cod'=>'ws','nombre'=>'Samoa','ico'=>'flag-icon-ws'],
			['cod'=>'kn','nombre'=>'San Cristóbal y Nieves','ico'=>'flag-icon-kn'],
			['cod'=>'sm','nombre'=>'San Marino','ico'=>'flag-icon-sm'],
			['cod'=>'vc','nombre'=>'San Vicente y las Granadinas','ico'=>'flag-icon-vc'],
			['cod'=>'lc','nombre'=>'Santa Lucía','ico'=>'flag-icon-lc'],
			['cod'=>'st','nombre'=>'Santo Tomé y Príncipe','ico'=>'flag-icon-st'],
			['cod'=>'sn','nombre'=>'Senegal','ico'=>'flag-icon-sn'],
			['cod'=>'rs','nombre'=>'Serbia','ico'=>'flag-icon-rs'],
			['cod'=>'sc','nombre'=>'Seychelles','ico'=>'flag-icon-sc'],
			['cod'=>'sl','nombre'=>'Sierra Leona','ico'=>'flag-icon-sl'],
			['cod'=>'sg','nombre'=>'Singapur','ico'=>'flag-icon-sg'],
			['cod'=>'so','nombre'=>'Somalia','ico'=>'flag-icon-so'],
			['cod'=>'lk','nombre'=>'Sri Lanka','ico'=>'flag-icon-lk'],
			['cod'=>'sz','nombre'=>'Suazilandia','ico'=>'flag-icon-sz'],
			['cod'=>'za','nombre'=>'Sudáfrica','ico'=>'flag-icon-za'],
			['cod'=>'sd','nombre'=>'Sudán','ico'=>'flag-icon-sd'],
			['cod'=>'ss','nombre'=>'Sudán del Sur','ico'=>'flag-icon-ss'],
			['cod'=>'se','nombre'=>'Suecia','ico'=>'flag-icon-se'],
			['cod'=>'ch','nombre'=>'Suiza','ico'=>'flag-icon-ch'],
			['cod'=>'sr','nombre'=>'Surinam','ico'=>'flag-icon-sr'],
			['cod'=>'th','nombre'=>'Tailandia','ico'=>'flag-icon-th'],
			['cod'=>'tj','nombre'=>'Tayikistán','ico'=>'flag-icon-tj'],
			['cod'=>'tl','nombre'=>'Timor-Leste','ico'=>'flag-icon-tl'],
			['cod'=>'tg','nombre'=>'Togo','ico'=>'flag-icon-tg'],
			['cod'=>'tk','nombre'=>'Tokelau','ico'=>'flag-icon-tk'],
			['cod'=>'to','nombre'=>'Tonga','ico'=>'flag-icon-to'],
			['cod'=>'tt','nombre'=>'Trinidad y Tobago','ico'=>'flag-icon-tt'],
			['cod'=>'tn','nombre'=>'Túnez','ico'=>'flag-icon-tn'],
			['cod'=>'tm','nombre'=>'Turkmenistán','ico'=>'flag-icon-tm'],
			['cod'=>'tr','nombre'=>'Turquía','ico'=>'flag-icon-tr'],
			['cod'=>'tv','nombre'=>'Tuvalu','ico'=>'flag-icon-tv'],
			['cod'=>'ua','nombre'=>'Ucrania','ico'=>'flag-icon-ua'],
			['cod'=>'ug','nombre'=>'Uganda','ico'=>'flag-icon-ug'],
			['cod'=>'uy','nombre'=>'Uruguay','ico'=>'flag-icon-uy'],
			['cod'=>'uz','nombre'=>'Uzbekistán','ico'=>'flag-icon-uz'],
			['cod'=>'vu','nombre'=>'Vanuatu','ico'=>'flag-icon-vu'],
			['cod'=>'ve','nombre'=>'Venezuela','ico'=>'flag-icon-ve'],
			['cod'=>'vn','nombre'=>'Vietnam','ico'=>'flag-icon-vn'],
			['cod'=>'ye','nombre'=>'Yemen','ico'=>'flag-icon-ye'],
			['cod'=>'dj','nombre'=>'Yibuti','ico'=>'flag-icon-dj'],
			['cod'=>'zm','nombre'=>'Zambia','ico'=>'flag-icon-zm'],
			['cod'=>'zw','nombre'=>'Zimbabue','ico'=>'flag-icon-zw']];

		$faker = Faker::create('es_VE');
		foreach ($paises as $key => $value) {
			DB::table('countries')->insert(array(
		   'name' => $value['nombre'],
				   'cod_iso2' => $value['cod'],
				   'ico' => $value['ico'],
		           'created_by' => $faker->numberBetween(1,10)
		    ));
		}
    }
}
